version: '3.8'

services:
  frontend:
    image: ghcr.io/maximecd/timetracker-web:main
    ports:
      - "3001:80"

  backend:
    image: ghcr.io/maximecd/timetracker-api:main
    ports:
      - "3002:8080"
    depends_on:
      - db
    environment:
      PORT: 8080
      SESSION_DRIVER: cookie
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_DATABASE: db
      HOST: 0.0.0.0
      LOG_LEVEL: info
      APP_KEY: 'orserseoirhjsiohvioshrioshiorvhseiorhih'
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: db
