name: Call Webhook when Deployments are Done

on:
  workflow_run:
    workflows: ['deploy-web.yml']
    types:
      - completed

jobs:
  call-webhook:
    runs-on: ubuntu-latest
    steps:
      - name: Call Webhook
        run: |
          curl -X POST -H "Authorization: Bearer ${{ secrets.WEBHOOK_TOKEN }}" https://coolify.maximecd.com/api/v1/deploy?uuid=e0ok0s8&force=false
