name: Deploy api

on:
  push:
    branches:
      - main
    paths:
      - 'apps/api/**'
      - 'packages/**'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: self-hosted
