name: Deploy api

on:
  push:
    branches:
      - main
    paths:
      - 'apps/api/**'
      - 'packages/**'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}-api

jobs:
  build-and-push-image:
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Packages
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=ref,event=tag

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          build-args: |
            APP_RELEASE=${{ github.sha }}
          platforms: linux/aarch64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          file: apps/api/Dockerfile
  call-webhook:
    runs-on: ubuntu-latest
    needs: build-and-push-image
    steps:
      - name: Call Webhook
        run: |
          curl --request GET --url "https://coolify.maximecd.com/api/v1/deploy?uuid=y4gcwcc&force=false" --header 'Authorization: Bearer ${{ secrets.WEBHOOK_TOKEN }}'
